---
name: setup-angle
description: |
  Set up a specific build of ANGLE in your Github Actions workflow running on
  macOS or Windows.
author: Erlangsters
branding:
  color: purple
  icon: code
inputs:
  branch:
    description: The ANGLE branch to use.
runs:
  using: node20
  main: setup-angle.js
