---
name: setup-angle
description: |
  Set up a specific build of ANGLE in your Github Actions workflow running on
  macOS or Windows.
author: Erlangsters
branding:
  color: purple
  icon: code
inputs:
  angle-branch:
    description: Branch of ANGLE to set up.
outputs:
  angle-branch:
    description: ANGLE branch that was installed.
  angle-location:
    description: The absolute path of the ANGLE installation location.
runs:
  using: node20
  main: setup-angle.js
